//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLyPhongLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONGVIEC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONGVIEC()
        {
            this.PHANCONGs = new HashSet<PHANCONG>();
        }
    
        public string ID { get; set; }
        public string TenCV { get; set; }
        public string MaDA { get; set; }
        public string TaiLieuCV { get; set; }
        public Nullable<int> CheckCV { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
    
        public virtual DUAN DUAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONG> PHANCONGs { get; set; }
    }
}
