//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLyPhongLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUAN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DUAN()
        {
            this.CONGVIECs = new HashSet<CONGVIEC>();
        }
    
        public string ID { get; set; }
        public string TenDuAn { get; set; }
        public string Nhom { get; set; }
        public string MaNQL { get; set; }
        public string TaiLieuDA { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
        public Nullable<int> CheckDA { get; set; }
        public string MoTa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CONGVIEC> CONGVIECs { get; set; }
        public virtual NGUOIQUANLY NGUOIQUANLY { get; set; }
        public virtual NHOM NHOM1 { get; set; }
        public override string ToString()
        {
            return this.ID;
        }

    }
}
