//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_QuanLyPhongLab.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONG
    {
        public string MaTV { get; set; }
        public string MaCV { get; set; }
        public Nullable<System.DateTime> NgayHoanThanh { get; set; }
    
        public virtual CONGVIEC CONGVIEC { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
